### ISSUE TITLE
Pytorch module not showing

### ISSUE THREAD

**Issue by danieldeidda** [fepegar/SlicerPyTorch#17]
Hi,
I am a very beginner with slicer. I am having issues to install extensions from the GUI but I manage to install a few from file. These extension need the pytorch extension which I have also installed, however I can't find pytorch in my modules. Am I doing something obviously wrong?

**Comment by lassoan** [comment]
You need to install extensions from the GUI. Only some modules in some extensions can be installed by simply downloading and adding the module paths.

You can follow these instructions:
https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#install-extensions
https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#install-extensions-without-network-connection

If you run into any issues that you cannot resolve then please post on the Slicer forum (https://discourse.slicer.org) describing exactly what you did, what you expected to happen, and what happened instead.
