### ISSUE TITLE
Failed test case due to missing attribute landmarksPath

### ISSUE THREAD

**Issue by jamesobutler** [fepegar/SlicerPyTorch#3]
See testing results at https://slicer.cdash.org/test/20203689
```
======================================================================
ERROR: test_PyTorchUtils (PyTorchUtils.PyTorchUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/D/P/S-0-E-b/PyTorch-build/lib/Slicer-4.13/qt-scripted-modules/PyTorchUtils.py", line 127, in tearDown
    self.landmarksPath.unlink()
AttributeError: 'PyTorchUtilsTest' object has no attribute 'landmarksPath'
```

Also a little weird that `light-the-torch` is pinning `pip` to a certain version (https://github.com/pmeier/light-the-torch/commit/24cd4744fac964923b0ad98a906cc67b725ab338) which is why Slicer it having to uninstall `pip` to use an older version.

**Comment by fepegar** [comment]
> See testing results at https://slicer.cdash.org/test/20203689

Thanks, @jamesobutler. I'm considering writing a GitHub Action to check every day for failing tests on CDash. Do you know if something like that exists? I wouldn't want to reinvent the wheel.

> Also a little weird that light-the-torch is pinning pip to a certain version (pmeier/light-the-torch@24cd474) which is why Slicer it having to uninstall pip to use an older version.

Yes. @pmeier must have a good reason for that!

**Comment by pmeier** [comment]
`light-the-torch` uses `pip` internals to find and install the right PyTorch distributions. Since `pip` doesn't keep BC on internals (rightfully so), `light-the-torch` needs to pin `pip` to the version it is working with. @jamesobutler If you want to use a newer `pip` version, I happily accept a patch for `light-the-torch` to upgrade the dependency.

**Comment by fepegar** [comment]
> Since pip doesn't keep BC on internals (rightfully so)

What does BC stand for?

**Comment by pieper** [comment]
>> Since pip doesn't keep BC on internals (rightfully so)

> What does BC stand for?

I'm gonna guess backward compatibility 😄

**Comment by fepegar** [comment]
Thanks, Steve!
