### ISSUE TITLE
OSError: [WinError 127] Error loading "torch_cuda_cpp.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by nnzzll** [fepegar/SlicerPyTorch#4]
I succesfully download the PyTorch module.
However, when I import torch,it returns a OSError below.

How can I fix this bug?
- Slicer Version:4.13.0-2021-11-20
- OS: Windows10
```
>>> import torch
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Lenovo\AppData\Local\NA-MIC\Slicer 4.13.0-2021-11-20\lib\Python\Lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "C:\Users\Lenovo\AppData\Local\NA-MIC\Slicer 4.13.0-2021-11-20\lib\Python\Lib\site-packages\torch\lib\torch_cuda_cpp.dll" or one of its dependencies.
```

**Comment by fepegar** [comment]
Please next open a new issue instead of editing the whole text. I have been investigating the reasons for your previous issue and have come here to find something completely different.

---

I'm not sure why you are getting this error. Can you reinstall Slicer and try again? It seems to be related to PyTorch, not this module specifically.

**Comment by pieper** [comment]
For the original `isatty` issue, see https://discourse.slicer.org/t/automated-brain-segmentation-into-white-matter-volume-gmv-and-csf-vol/19322/7

**Comment by fepegar** [comment]
Thanks, Steve. I thought this error looked familiar! More references:
- https://github.com/MeVisLab/pythonqt/issues/48
- https://github.com/MeVisLab/pythonqt/pull/49
- https://github.com/MeVisLab/pythonqt/pull/50
- https://github.com/Slicer/Slicer/issues/5705
- https://github.com/Slicer/Slicer/pull/5711

**Comment by lassoan** [comment]
I get this error when installing PyTorch CUDA version that does not match system CUDA version. The new GUI of the module makes it easy to uninstall PyTorch and then install PyTorch with the correct CUDA version.

**Comment by fepegar** [comment]
Thanks again, @lassoan!
