### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by fepegar** [fepegar/SlicerPyTorch#5]
I asked the PyTorch team if they are happy with the logo. They said:
> Using the PyTorch logo is allowed but there are some guidelines that you would need to follow. For example, altering the PyTorch logo to create another logo is not allowed and also there need to be clear spaces around the PyTorch logo.
> Since you have already created the logo, it might be difficult to update but would any of the recommendations below work?
> ![unnamed](https://user-images.githubusercontent.com/12688084/142877940-8678442c-6b09-4f22-9318-8d15d12bdf92.png)

In another iteration, they said they would also be happy with the Slicer logo being smaller, or the same size, as the PyTorch logo. Basically, they need to be separate.

@lassoan, @pieper, @jcfr what do you think is best? I asked them if they were happy with the logo before sharing the extension on e.g. the PyTorch forum.

**Comment by pieper** [comment]
We added some guidelines here and there's some discussion of the thought process.

https://github.com/Slicer/Slicer/pull/5957/files

Basically similar guidelines to the pytorch policy.  We wanted to allow some freedom for ideas like the [SlicerAstro logo](https://github.com/Punzo/SlicerAstro/wiki).  

I'm fine with any of the proposals.  I think I like the two towards the top a little better.

**Comment by lassoan** [comment]
There are many extensions that implement interface to another system/library, so it is worth having a discussion about this and come up with a recommendation for all such extensions.

One of the most prominent use of the logo is in the extensions catalog. Having the Slicer logo showing up there would be just noise that would make it harder to recognize the actual logo.

Most current icons just use the third-party icon:

![](https://raw.githubusercontent.com/QIICR/dcmqi/master/dcmqi.png)
![](https://raw.githubusercontent.com/lassoan/SlicerElastix/master/SlicerElastix.png)
![](https://raw.githubusercontent.com/KitwareMedical/SlicerLookingGlass/master/LookingGlass/Resources/Icons/LookingGlass.png)
![](https://raw.githubusercontent.com/PerkLab/SlicerOpenAnatomy/master/SlicerOpenAnatomy.png)
![](https://raw.githubusercontent.com/fepegar/SlicerTorchIO/master/TorchIOTransforms/Resources/Icons/TorchIOTransforms.png)
![](https://raw.githubusercontent.com/flywheel-apps/SlicerFlywheelConnect/master/Images/favicon.png)

There are a few creatively mixed icons:

![](https://raw.githubusercontent.com/pzaffino/SlicerArduinoController/master/ArduinoController.png)
![](https://raw.githubusercontent.com/Slicer/SlicerJupyter/master/SlicerJupyterLogo.png)

System integration services such as IFTTT, Zapier, Google Assistant, etc. seem to simply use the third-party logos:

![image](https://user-images.githubusercontent.com/307929/142897538-2d072827-81ca-4391-a870-242ada7872bb.png)

![image](https://user-images.githubusercontent.com/307929/142897899-347c2943-b6be-4fb0-b335-9fac0ca5984f.png)

![image](https://user-images.githubusercontent.com/307929/142899676-86c34f47-2e05-48ce-8c7d-aca992cee440.png)

![image](https://user-images.githubusercontent.com/307929/142901168-add83269-67de-405e-9bc6-7f6329ac151f.png)

**Overall, for me it seems that in the extensions catalog the best solution would be to use the third-party logo as is.** In the extension's github project page a side-by-side logo as recommended above could make sense.

**Comment by fepegar** [comment]
@lassoan I think that makes sense.

Pinging @wookim3 from Meta.

**Comment by fepegar** [comment]
I just got an email from @wookim3 giving us the green light for the current logo:

> Hi Fernando –
I’m so sorry for getting back to you late on this. You can go live with the current logo and modifications doesn’t have to be made at this point. I was out for the extended time and finally back in the office.
Thank you,
Woo

Closing this for now, feel free to reopen if you'd like the logo to change.
